package com.sda.algorytmy.lista;

public class ListTest {
    public static void main(String[] args) {
        MyList<Integer> list = new ListImpl<>();
        list.add(5);
        list.add(10);
        list.add(15);
        list.add(20);
        list.add(25);
        list.add(30);
        list.add(35);
        list.add(40);
        list.add(45);
        list.add(50);
        list.add(55);
        list.add(5);
        list.add(10);
        list.add(15);
        list.add(20);
        list.add(25);
        list.add(30);
        list.add(35);
        list.add(40);
        list.add(45);
        list.add(50);
        list.add(55);
        list.add(5);
        list.add(10);
        list.add(15);
        list.add(20);
        list.add(25);
        list.add(30);
        list.add(35);
        list.add(40);
        list.add(45);
        list.add(50);
        list.add(55);
        list.add(5);
        list.add(10);
        list.add(15);
        list.add(20);
        list.add(25);
        list.add(30);
        list.add(35);
        list.add(40);
        list.add(45);
        list.add(50);
        list.add(55);
        list.add(5);
        list.add(10);
        list.add(15);
        list.add(20);
        list.add(25);
        list.add(30);
        list.add(35);
        list.add(40);
        list.add(45);
        list.add(50);
        list.add(55);
        list.add(5);
        list.add(10);
        list.add(15);
        list.add(20);
        list.add(25);
        list.add(30);
        list.add(35);
        list.add(40);
        list.add(45);
        list.add(50);
        list.add(55);


        MyList<Integer> list1 = new LinkedListImpl<>();
        list1.add(45);
        list1.add(50);
        list1.add(55);
        System.out.println(list1);
    }
}
